const healthAdvices = {
    "fever": "in case of fever , you measure temperature and accordingly should have a visit to doctor",
    "weight": "To control weight, maintain a balanced diet, exercise regularly, and stay hydrated.",
    "cholesterol": "To manage cholesterol, avoid trans fats, eat more omega-3 fatty acids, and exercise regularly.",
    "blood pressure": "To lower blood pressure, reduce sodium intake, exercise regularly, and manage stress.",
    "diabetes": "To manage diabetes, monitor blood sugar levels, eat a balanced diet, and exercise regularly.",
    "heart health": "To improve heart health, eat a heart-healthy diet, exercise regularly, and avoid smoking.",
    "mental health": "To support mental health, practice mindfulness, get regular exercise, and maintain social connections.",
    "sleep": "To improve sleep, establish a regular sleep schedule, create a restful environment, and avoid caffeine before bed.",
    "hydration": "To stay hydrated, drink at least 8 glasses of water a day and monitor your urine color.",
    "exercise": "To maintain physical fitness, engage in at least 150 minutes of moderate exercise per week.",
    "nutrition": "For good nutrition, eat a variety of fruits, vegetables, whole grains, and lean proteins.",
    "smoking": "To quit smoking, seek support, use nicotine replacement therapy, and avoid triggers.",
    "alcohol": "To reduce alcohol intake, set limits, avoid triggers, and seek support if needed.",
    "stress": "To manage stress, practice relaxation techniques, exercise regularly, and get enough sleep.",
    "skin care": "For healthy skin, use sunscreen, moisturize daily, and stay hydrated.",
    "digestion": "To improve digestion, eat a high-fiber diet, stay hydrated, and avoid processed foods.",
    "immune system": "To boost the immune system, eat a balanced diet, get regular exercise, and get enough sleep.",
    "vision": "To protect your vision, take regular breaks from screens, wear sunglasses, and get regular eye exams.",
    "hearing": "To protect your hearing, avoid loud noises, use ear protection, and get regular hearing checks.",
    "dental health": "For good dental health, brush and floss daily, limit sugary foods, and visit the dentist regularly.",
    "bone health": "To maintain bone health, eat a diet rich in calcium and vitamin D, and engage in weight-bearing exercise.",
    "joint health": "To support joint health, maintain a healthy weight, stay active, and avoid injury.",
    "muscle health": "To maintain muscle health, engage in strength training exercises and eat enough protein.",
    "back pain": "To prevent back pain, maintain good posture, stay active, and avoid heavy lifting.",
    "neck pain": "To relieve neck pain, practice good posture, use ergonomic furniture, and do stretching exercises.",
    "headaches": "To reduce headaches, stay hydrated, manage stress, and get enough sleep.",
    "migraines": "To prevent migraines, avoid triggers, manage stress, and maintain a regular sleep schedule.",
    "cold and flu": "To prevent colds and flu, wash hands regularly, avoid close contact with sick people, and get vaccinated.",
    "allergies": "To manage allergies, avoid triggers, take antihistamines, and keep windows closed during high pollen seasons.",
    "asthma": "To manage asthma, use prescribed inhalers, avoid triggers, and monitor your symptoms.",
    "COPD": "To manage COPD, avoid smoking, use prescribed medications, and get regular exercise.",
    "arthritis": "To manage arthritis, stay active, maintain a healthy weight, and use anti-inflammatory medications.",
    "osteoporosis": "To prevent osteoporosis, eat a diet rich in calcium and vitamin D, and engage in weight-bearing exercise.",
    "kidney health": "To maintain kidney health, stay hydrated, eat a balanced diet, and avoid excessive salt.",
    "liver health": "To maintain liver health, avoid excessive alcohol, eat a balanced diet, and get regular exercise.",
    "digestive health": "To maintain digestive health, eat a high-fiber diet, stay hydrated, and avoid processed foods.",
    "gut health": "To support gut health, eat probiotics, avoid processed foods, and manage stress.",
    "hydration tips": "To stay hydrated, drink at least 8 glasses of water a day, and consume water-rich foods like fruits and vegetables.",
    "fiber intake": "For adequate fiber intake, eat fruits, vegetables, whole grains, and legumes.",
    "healthy fats": "Include healthy fats in your diet like avocados, nuts, and olive oil.",
    "vitamin D": "Get enough vitamin D through sunlight exposure, fortified foods, and supplements if needed.",
    "protein intake": "Ensure adequate protein intake by including lean meats, beans, and nuts in your diet.",
    "calcium intake": "For calcium, consume dairy products, leafy greens, and fortified foods.",
    "iron intake": "To boost iron intake, eat red meat, beans, and fortified cereals.",
    "vitamin C": "Get enough vitamin C through citrus fruits, berries, and bell peppers.",
    "weight gain": "To gain weight healthily, increase calorie intake with nutrient-dense foods and strength training exercises.",
    "weight loss": "For weight loss, reduce calorie intake, increase physical activity, and avoid processed foods.",
    "boost energy": "To boost energy, eat a balanced diet, get regular exercise, and ensure adequate sleep.",
    "reduce fatigue": "To reduce fatigue, manage stress, stay hydrated, and maintain a balanced diet.",
    "healthy aging": "For healthy aging, stay active, eat a balanced diet, and keep your mind engaged.",
    "memory improvement": "To improve memory, engage in mental exercises, get regular physical activity, and maintain social connections.",
    "cognitive health": "Support cognitive health by eating a balanced diet, staying physically active, and getting enough sleep.",
    "vision improvement": "To improve vision, eat foods rich in vitamin A, take breaks from screens, and get regular eye exams.",
    "hearing improvement": "To improve hearing, avoid loud noises, use hearing protection, and get regular hearing checks.",
    "prevent infections": "To prevent infections, wash hands regularly, get vaccinated, and avoid close contact with sick people.",
    "posture improvement": "To improve posture, sit up straight, use ergonomic furniture, and do strengthening exercises.",
    "reduce swelling": "To reduce swelling, elevate the affected area, use cold compresses, and stay hydrated.",
    "wound healing": "For wound healing, keep the area clean, use antiseptics, and eat a nutrient-rich diet.",
    "prevent dehydration": "To prevent dehydration, drink water regularly, especially in hot weather and during exercise.",
    "manage dehydration": "To manage dehydration, drink oral rehydration solutions and avoid caffeine and alcohol.",
    "mental clarity": "For mental clarity, get enough sleep, eat a balanced diet, and practice mindfulness.",
    "relieve constipation": "To relieve constipation, increase fiber intake, stay hydrated, and exercise regularly.",
    "diarrhea management": "To manage diarrhea, stay hydrated, eat bland foods, and avoid dairy and fatty foods.",
    "stomach pain": "For stomach pain, avoid spicy foods, eat smaller meals, and stay hydrated.",
    "reduce bloating": "To reduce bloating, avoid carbonated drinks, eat slowly, and stay hydrated.",
    "improve metabolism": "To improve metabolism, eat protein-rich foods, drink green tea, and exercise regularly.",
    "heartburn relief": "For heartburn relief, avoid spicy foods, eat smaller meals, and stay upright after eating.",
    "ulcer management": "To manage ulcers, avoid NSAIDs, eat smaller meals, and avoid spicy foods.",
    "gallbladder health": "For gallbladder health, eat a low-fat diet, stay hydrated, and avoid rapid weight loss.",
    "pancreas health": "To support pancreas health, avoid alcohol, eat a balanced diet, and stay hydrated.",
    "adrenal health": "For adrenal health, manage stress, eat a balanced diet, and get enough sleep.",
    "thyroid health": "To support thyroid health, eat iodine-rich foods, avoid goitrogens, and get regular checkups.",
    "pituitary health": "For pituitary health, maintain a balanced diet, stay hydrated, and manage stress.",
    "hormonal balance": "To maintain hormonal balance, eat a balanced diet, get regular exercise, and manage stress.",
    "reduce inflammation": "To reduce inflammation, eat anti-inflammatory foods, exercise regularly, and avoid smoking.",
    "immune boost": "To boost your immune system, eat a balanced diet, get enough sleep, and manage stress.",
    "lung health": "For lung health, avoid smoking, get regular exercise, and avoid pollutants.",
    "bronchitis management": "To manage bronchitis, stay hydrated, use a humidifier, and avoid smoke and fumes.",
    "reduce fever": "To reduce fever, stay hydrated, rest, and use fever-reducing medications if necessary.",
    "manage chills": "To manage chills, stay warm, rest, and drink warm fluids.",
    "cough relief": "For cough relief, stay hydrated, use a humidifier, and take over-the-counter cough medications.",
    "sore throat relief": "For sore throat relief, drink warm liquids, use throat lozenges, and avoid irritants.",
    "earache relief": "For earache relief, use warm compresses, avoid loud noises, and consult a doctor if needed.",
    "sinus infection relief": "For sinus infection relief, stay hydrated, use a humidifier, and take over-the-counter decongestants.",
    "nasal congestion relief": "For nasal congestion relief, use saline sprays, stay hydrated, and use a humidifier.",
    "allergy relief": "For allergy relief, avoid triggers, take antihistamines, and keep windows closed during high pollen seasons.",
    "eczema relief": "For eczema relief, use moisturizers, avoid irritants, and use prescribed medications if needed.",
    "psoriasis relief": "For psoriasis relief, use moisturizers, avoid triggers, and use prescribed medications if needed.",
    "acne management": "To manage acne, keep your skin clean, avoid greasy foods, and use acne treatments.",
    "reduce wrinkles": "To reduce wrinkles, use sunscreen, moisturize regularly, and avoid smoking.",
    "hair health": "For healthy hair, eat a balanced diet, avoid harsh chemicals, and get regular trims.",
    "nail health": "For healthy nails, keep them clean, avoid biting, and use moisturizers.",
    "foot care": "For foot care, keep your feet clean, wear comfortable shoes, and avoid walking barefoot in public places.",
    "hand care": "For hand care, keep your hands clean, use moisturizers, and avoid harsh chemicals.",
    "eye care": "For eye care, take regular breaks from screens, wear sunglasses, and get regular eye exams.",
    "ear care": "For ear care, avoid loud noises, keep your ears clean, and get regular hearing checks.",
    "dental care": "For dental care, brush and floss daily, limit sugary foods, and visit the dentist regularly.",
    "nose care": "For nose care, avoid irritants, use saline sprays, and stay hydrated.",
    "throat care": "For throat care, avoid irritants, stay hydrated, and use throat lozenges if needed.",
    "vitamin A": "Vitamin A is essential for vision, immune function, and skin health. Good sources include carrots, sweet potatoes, and spinach.",
    "vitamin B1 (Thiamine)": "Vitamin B1 is important for energy metabolism and nerve function. Good sources include whole grains, pork, and legumes.",
    "vitamin B2 (Riboflavin)": "Vitamin B2 helps with energy production and skin health. Found in eggs, milk, and green vegetables.",
    "vitamin B3 (Niacin)": "Vitamin B3 supports energy metabolism and DNA repair. Found in meat, fish, and whole grains.",
    "vitamin B5 (Pantothenic Acid)": "Vitamin B5 is essential for synthesizing coenzyme A. Good sources include chicken, beef, and avocados.",
    "vitamin B6 (Pyridoxine)": "Vitamin B6 is vital for brain health and metabolism. Found in fish, beef liver, and potatoes.",
    "vitamin B7 (Biotin)": "Vitamin B7 supports hair, skin, and nail health. Found in eggs, nuts, and seeds.",
    "vitamin B9 (Folate)": "Folate is crucial for cell division and pregnancy health. Found in leafy greens, legumes, and citrus fruits.",
    "vitamin B12 (Cobalamin)": "Vitamin B12 is important for nerve function and red blood cell production. Found in meat, dairy, and fortified cereals.",
    "vitamin C": "Vitamin C is essential for immune function and skin health. Found in citrus fruits, berries, and bell peppers.",
    "vitamin D": "Vitamin D supports bone health and immune function. Found in fatty fish, fortified milk, and sunlight exposure.",
    "vitamin E": "Vitamin E acts as an antioxidant, protecting cells from damage. Found in nuts, seeds, and spinach.",
    "vitamin K": "Vitamin K is essential for blood clotting and bone health. Found in leafy greens, broccoli, and Brussels sprouts.",
    // Blood Tests
    "complete blood count (CBC)": "A CBC measures various components of your blood, including red blood cells, white blood cells, and platelets. It's used to diagnose a variety of conditions.",
    "basic metabolic panel (BMP)": "A BMP checks levels of different chemicals in the blood, such as glucose, calcium, and electrolytes, to assess organ function.",
    "comprehensive metabolic panel (CMP)": "A CMP includes the BMP and additional protein and liver enzyme tests.",
    "lipid panel": "A lipid panel measures cholesterol levels, including LDL, HDL, and triglycerides, to assess heart disease risk.",
    "liver function tests": "These tests measure liver enzymes and proteins to assess liver health.",
    "thyroid function tests": "These tests measure thyroid hormones to diagnose thyroid disorders.",
    "hemoglobin A1c": "This test measures average blood glucose levels over the past 2-3 months to monitor diabetes.",
    "vitamin D test": "This test measures vitamin D levels to check for deficiency or toxicity.",
    "iron panel": "An iron panel measures iron levels and related markers to diagnose anemia or iron overload.",
    "kidney function tests": "These tests measure waste products in the blood to assess kidney health.",
    // Blood Pressure
    "high blood pressure": "High blood pressure, or hypertension, increases the risk of heart disease and stroke. Maintain a healthy diet, exercise regularly, and limit salt intake to manage blood pressure.",
    "low blood pressure": "Low blood pressure, or hypotension, can cause dizziness and fainting. Stay hydrated, eat small frequent meals, and avoid standing for long periods.",
    "normal blood pressure": "Normal blood pressure is around 120/80 mmHg. Maintain a healthy lifestyle to keep your blood pressure within this range.",
    // Weight
    "healthy weight": "Maintain a healthy weight by balancing calorie intake with physical activity. Eat a balanced diet and exercise regularly.",
    "weight gain": "To gain weight healthily, increase your calorie intake with nutrient-dense foods and strength training exercises.",
    "weight loss": "For weight loss, reduce calorie intake, increase physical activity, and avoid processed foods. Focus on a balanced diet with plenty of fruits, vegetables, lean proteins, and whole grains.",
    // Height
    "height growth": "Height growth in children and adolescents can be supported by a balanced diet, regular exercise, and adequate sleep. Genetics also play a significant role in determining height.",
    // Cholesterol
    "high cholesterol": "High cholesterol increases the risk of heart disease. Lower cholesterol levels by eating a diet low in saturated fats and trans fats, exercising regularly, and avoiding smoking.",
    "low cholesterol": "Low cholesterol can be achieved through a healthy diet, regular physical activity, and maintaining a healthy weight.",
    "normal cholesterol": "Maintain normal cholesterol levels by eating a balanced diet, exercising regularly, and avoiding smoking and excessive alcohol consumption.",
    // Nutritional Advice
    "fiber-rich foods": "Fiber-rich foods include fruits, vegetables, whole grains, and legumes. Fiber helps with digestion, lowers cholesterol, and controls blood sugar levels.",
    "protein-rich foods": "Protein-rich foods include lean meats, fish, eggs, dairy, beans, and nuts. Protein is essential for muscle repair, immune function, and overall health.",
    "healthy fats": "Healthy fats include avocados, nuts, seeds, and olive oil. These fats support brain health, hormone production, and cell function.",
    "lactose-free foods": "Lactose-free foods include lactose-free dairy products, plant-based milks, and foods naturally low in lactose such as fruits, vegetables, and meats.",
    // Specific Food Advice
    "foods high in vitamin A": "Foods high in vitamin A include carrots, sweet potatoes, spinach, and apricots.",
    "foods high in vitamin B": "Foods high in vitamin B include whole grains, meat, eggs, dairy, legumes, seeds, and leafy greens.",
    "foods high in vitamin C": "Foods high in vitamin C include citrus fruits, strawberries, bell peppers, and broccoli.",
    "foods high in vitamin D": "Foods high in vitamin D include fatty fish, fortified dairy products, and mushrooms.",
    "foods high in vitamin E": "Foods high in vitamin E include nuts, seeds, spinach, and broccoli.",
    "foods high in vitamin K": "Foods high in vitamin K include leafy greens, broccoli, Brussels sprouts, and green beans.",
    // Additional Detailed Information
    "reduce inflammation": "To reduce inflammation, eat anti-inflammatory foods like berries, fatty fish, and green leafy vegetables. Avoid processed foods, sugar, and trans fats.",
    "boost immunity": "Boost your immunity by eating a diet rich in fruits, vegetables, whole grains, and lean proteins. Stay hydrated, get enough sleep, and manage stress.",
    "improve digestion": "Improve digestion by eating high-fiber foods, staying hydrated, and incorporating probiotics like yogurt and fermented foods into your diet.",
    "support mental health": "Support mental health by maintaining a balanced diet, staying physically active, getting enough sleep, and seeking social support.",
    "enhance skin health": "Enhance skin health by staying hydrated, eating a diet rich in antioxidants, and protecting your skin from the sun.",
    "bone health": "For bone health, ensure adequate intake of calcium and vitamin D, engage in weight-bearing exercises, and avoid smoking and excessive alcohol.",
    "reduce stress": "Reduce stress by practicing mindfulness, staying physically active, getting enough sleep, and seeking social support.",
    "improve sleep": "Improve sleep by maintaining a regular sleep schedule, creating a relaxing bedtime routine, and avoiding caffeine and electronics before bed.",
    "heart health": "Maintain heart health by eating a balanced diet low in saturated fats, exercising regularly, avoiding smoking, and managing stress.",
    "eye health": "Support eye health by eating foods rich in vitamin A, such as carrots and leafy greens, and protecting your eyes from UV light.",
  };
  
  function refineQuestion(question) {
    return question.toLowerCase().replace(/[^a-z0-9\s]/gi, '').trim();
  }
  
  exports.getHealthAdvice = async (req, res) => {
    const { question } = req.body;
  
    try {
      const refinedQuestion = refineQuestion(question);
      const key = Object.keys(healthAdvices).find(k => refinedQuestion.includes(k.toLowerCase()));
      if (key) {
        res.status(200).json({ advice: healthAdvices[key] });
      } else {
        res.status(404).json({ error: 'No advice found for your query.' });
      }
    } catch (error) {
      console.error('Error fetching health advice:', error);
      res.status(500).json({ error: 'An error occurred while fetching health advice.' });
    }
  };
  