const healthAdvices = {
  "fever": "in case of fever , you measure temperature and accordingly should have a visit to doctor",
  "weight": "To control weight, maintain a balanced diet, exercise regularly, and stay hydrated.",
  "cholesterol": "To manage cholesterol, avoid trans fats, eat more omega-3 fatty acids, and exercise regularly.",
  "blood pressure": "To lower blood pressure, reduce sodium intake, exercise regularly, and manage stress.",
  "diabetes": "To manage diabetes, monitor blood sugar levels, eat a balanced diet, and exercise regularly.",
  "heart health": "To improve heart health, eat a heart-healthy diet, exercise regularly, and avoid smoking.",
  "mental health": "To support mental health, practice mindfulness, get regular exercise, and maintain social connections.",
  "sleep": "To improve sleep, establish a regular sleep schedule, create a restful environment, and avoid caffeine before bed.",
  "hydration": "To stay hydrated, drink at least 8 glasses of water a day and monitor your urine color.",
  "exercise": "To maintain physical fitness, engage in at least 150 minutes of moderate exercise per week.",
  "nutrition": "For good nutrition, eat a variety of fruits, vegetables, whole grains, and lean proteins.",
  "smoking": "To quit smoking, seek support, use nicotine replacement therapy, and avoid triggers.",
  "alcohol": "To reduce alcohol intake, set limits, avoid triggers, and seek support if needed.",
  "stress": "To manage stress, practice relaxation techniques, exercise regularly, and get enough sleep.",
  "skin care": "For healthy skin, use sunscreen, moisturize daily, and stay hydrated.",
  "digestion": "To improve digestion, eat a high-fiber diet, stay hydrated, and avoid processed foods.",
  "immune system": "To boost the immune system, eat a balanced diet, get regular exercise, and get enough sleep.",
  "vision": "To protect your vision, take regular breaks from screens, wear sunglasses, and get regular eye exams.",
  "hearing": "To protect your hearing, avoid loud noises, use ear protection, and get regular hearing checks.",
  "dental health": "For good dental health, brush and floss daily, limit sugary foods, and visit the dentist regularly.",
  "bone health": "To maintain bone health, eat a diet rich in calcium and vitamin D, and engage in weight-bearing exercise.",
  "joint health": "To support joint health, maintain a healthy weight, stay active, and avoid injury.",
  "muscle health": "To maintain muscle health, engage in strength training exercises and eat enough protein.",
  "back pain": "To prevent back pain, maintain good posture, stay active, and avoid heavy lifting.",
  "neck pain": "To relieve neck pain, practice good posture, use ergonomic furniture, and do stretching exercises.",
  "headaches": "To reduce headaches, stay hydrated, manage stress, and get enough sleep.",
  "migraines": "To prevent migraines, avoid triggers, manage stress, and maintain a regular sleep schedule.",
  "cold and flu": "To prevent colds and flu, wash hands regularly, avoid close contact with sick people, and get vaccinated.",
  "allergies": "To manage allergies, avoid triggers, take antihistamines, and keep windows closed during high pollen seasons.",
  "asthma": "To manage asthma, use prescribed inhalers, avoid triggers, and monitor your symptoms.",
  "COPD": "To manage COPD, avoid smoking, use prescribed medications, and get regular exercise.",
  "arthritis": "To manage arthritis, stay active, maintain a healthy weight, and use anti-inflammatory medications.",
  "osteoporosis": "To prevent osteoporosis, eat a diet rich in calcium and vitamin D, and engage in weight-bearing exercise.",
  "kidney health": "To maintain kidney health, stay hydrated, eat a balanced diet, and avoid excessive salt.",
  "liver health": "To maintain liver health, avoid excessive alcohol, eat a balanced diet, and get regular exercise.",
  "digestive health": "To maintain digestive health, eat a high-fiber diet, stay hydrated, and avoid processed foods.",
  "gut health": "To support gut health, eat probiotics, avoid processed foods, and manage stress.",
  "hydration tips": "To stay hydrated, drink at least 8 glasses of water a day, and consume water-rich foods like fruits and vegetables.",
  "fiber intake": "For adequate fiber intake, eat fruits, vegetables, whole grains, and legumes.",
  "healthy fats": "Include healthy fats in your diet like avocados, nuts, and olive oil.",
  "vitamin D": "Get enough vitamin D through sunlight exposure, fortified foods, and supplements if needed.",
  "protein intake": "Ensure adequate protein intake by including lean meats, beans, and nuts in your diet.",
  "calcium intake": "For calcium, consume dairy products, leafy greens, and fortified foods.",
  "iron intake": "To boost iron intake, eat red meat, beans, and fortified cereals.",
  "vitamin C": "Get enough vitamin C through citrus fruits, berries, and bell peppers.",
  "weight gain": "To gain weight healthily, increase calorie intake with nutrient-dense foods and strength training exercises.",
  "weight loss": "For weight loss, reduce calorie intake, increase physical activity, and avoid processed foods.",
  "boost energy": "To boost energy, eat a balanced diet, get regular exercise, and ensure adequate sleep.",
  "reduce fatigue": "To reduce fatigue, manage stress, stay hydrated, and maintain a balanced diet.",
  "healthy aging": "For healthy aging, stay active, eat a balanced diet, and keep your mind engaged.",
  "memory improvement": "To improve memory, engage in mental exercises, get regular physical activity, and maintain social connections.",
  "cognitive health": "Support cognitive health by eating a balanced diet, staying physically active, and getting enough sleep.",
  "vision improvement": "To improve vision, eat foods rich in vitamin A, take breaks from screens, and get regular eye exams.",
  "hearing improvement": "To improve hearing, avoid loud noises, use hearing protection, and get regular hearing checks.",
  "prevent infections": "To prevent infections, wash hands regularly, get vaccinated, and avoid close contact with sick people.",
  "posture improvement": "To improve posture, sit up straight, use ergonomic furniture, and do strengthening exercises.",
  "reduce swelling": "To reduce swelling, elevate the affected area, use cold compresses, and stay hydrated.",
  "wound healing": "For wound healing, keep the area clean, use antiseptics, and eat a nutrient-rich diet.",
  "prevent dehydration": "To prevent dehydration, drink water regularly, especially in hot weather and during exercise.",
  "manage dehydration": "To manage dehydration, drink oral rehydration solutions and avoid caffeine and alcohol.",
  "mental clarity": "For mental clarity, get enough sleep, eat a balanced diet, and practice mindfulness.",
  "relieve constipation": "To relieve constipation, increase fiber intake, stay hydrated, and exercise regularly.",
  "diarrhea management": "To manage diarrhea, stay hydrated, eat bland foods, and avoid dairy and fatty foods.",
  "stomach pain": "For stomach pain, avoid spicy foods, eat smaller meals, and stay hydrated.",
  "reduce bloating": "To reduce bloating, avoid carbonated drinks, eat slowly, and stay hydrated.",
  "improve metabolism": "To improve metabolism, eat protein-rich foods, drink green tea, and exercise regularly.",
  "heartburn relief": "For heartburn relief, avoid spicy foods, eat smaller meals, and stay upright after eating.",
  "ulcer management": "To manage ulcers, avoid NSAIDs, eat smaller meals, and avoid spicy foods.",
  "gallbladder health": "For gallbladder health, eat a low-fat diet, stay hydrated, and avoid rapid weight loss.",
  "pancreas health": "To support pancreas health, avoid alcohol, eat a balanced diet, and stay hydrated.",
  "adrenal health": "For adrenal health, manage stress, eat a balanced diet, and get enough sleep.",
  "thyroid health": "To support thyroid health, eat iodine-rich foods, avoid goitrogens, and get regular checkups.",
  "pituitary health": "For pituitary health, maintain a balanced diet, stay hydrated, and manage stress.",
  "hormonal balance": "To maintain hormonal balance, eat a balanced diet, get regular exercise, and manage stress.",
  "reduce inflammation": "To reduce inflammation, eat anti-inflammatory foods, exercise regularly, and avoid smoking.",
  "immune boost": "To boost your immune system, eat a balanced diet, get enough sleep, and manage stress.",
  "lung health": "For lung health, avoid smoking, get regular exercise, and avoid pollutants.",
  "bronchitis management": "To manage bronchitis, stay hydrated, use a humidifier, and avoid smoke and fumes.",
  "reduce fever": "To reduce fever, stay hydrated, rest, and use fever-reducing medications if necessary.",
  "manage chills": "To manage chills, stay warm, rest, and drink warm fluids.",
  "cough relief": "For cough relief, stay hydrated, use a humidifier, and take over-the-counter cough medications.",
  "sore throat relief": "For sore throat relief, drink warm liquids, use throat lozenges, and avoid irritants.",
  "earache relief": "For earache relief, use warm compresses, avoid loud noises, and consult a doctor if needed.",
  "sinus infection relief": "For sinus infection relief, stay hydrated, use a humidifier, and take over-the-counter decongestants.",
  "nasal congestion relief": "For nasal congestion relief, use saline sprays, stay hydrated, and use a humidifier.",
  "allergy relief": "For allergy relief, avoid triggers, take antihistamines, and keep windows closed during high pollen seasons.",
  "eczema relief": "For eczema relief, use moisturizers, avoid irritants, and use prescribed medications if needed.",
  "psoriasis relief": "For psoriasis relief, use moisturizers, avoid triggers, and use prescribed medications if needed.",
  "acne management": "To manage acne, keep your skin clean, avoid greasy foods, and use acne treatments.",
  "reduce wrinkles": "To reduce wrinkles, use sunscreen, moisturize regularly, and avoid smoking.",
  "hair health": "For healthy hair, eat a balanced diet, avoid harsh chemicals, and get regular trims.",
  "nail health": "For healthy nails, keep them clean, avoid biting, and use moisturizers.",
  "foot care": "For foot care, keep your feet clean, wear comfortable shoes, and avoid walking barefoot in public places.",
  "hand care": "For hand care, keep your hands clean, use moisturizers, and avoid harsh chemicals.",
  "eye care": "For eye care, take regular breaks from screens, wear sunglasses, and get regular eye exams.",
  "ear care": "For ear care, avoid loud noises, keep your ears clean, and get regular hearing checks.",
  "dental care": "For dental care, brush and floss daily, limit sugary foods, and visit the dentist regularly.",
  "nose care": "For nose care, avoid irritants, use saline sprays, and stay hydrated.",
  "throat care": "For throat care, avoid irritants, stay hydrated, and use throat lozenges if needed.",
  "vitamin A": "Vitamin A is essential for vision, immune function, and skin health. Good sources include carrots, sweet potatoes, and spinach.",
  "vitamin B1 (Thiamine)": "Vitamin B1 is important for energy metabolism and nerve function. Good sources include whole grains, pork, and legumes.",
  "vitamin B2 (Riboflavin)": "Vitamin B2 helps with energy production and skin health. Found in eggs, milk, and green vegetables.",
  "vitamin B3 (Niacin)": "Vitamin B3 supports energy metabolism and DNA repair. Found in meat, fish, and whole grains.",
  "vitamin B5 (Pantothenic Acid)": "Vitamin B5 is essential for synthesizing coenzyme A. Good sources include chicken, beef, and avocados.",
  "vitamin B6 (Pyridoxine)": "Vitamin B6 is vital for brain health and metabolism. Found in fish, beef liver, and potatoes.",
  "vitamin B7 (Biotin)": "Vitamin B7 supports hair, skin, and nail health. Found in eggs, nuts, and seeds.",
  "vitamin B9 (Folate)": "Folate is crucial for cell division and pregnancy health. Found in leafy greens, legumes, and citrus fruits.",
  "vitamin B12 (Cobalamin)": "Vitamin B12 is important for nerve function and red blood cell production. Found in meat, dairy, and fortified cereals.",
  "vitamin C": "Vitamin C is essential for immune function and skin health. Found in citrus fruits, berries, and bell peppers.",
  "vitamin D": "Vitamin D supports bone health and immune function. Found in fatty fish, fortified milk, and sunlight exposure.",
  "vitamin E": "Vitamin E acts as an antioxidant, protecting cells from damage. Found in nuts, seeds, and spinach.",
  "vitamin K": "Vitamin K is essential for blood clotting and bone health. Found in leafy greens, broccoli, and Brussels sprouts.",
  // Blood Tests
  "complete blood count (CBC)": "A CBC measures various components of your blood, including red blood cells, white blood cells, and platelets. It's used to diagnose a variety of conditions.",
  "basic metabolic panel (BMP)": "A BMP checks levels of different chemicals in the blood, such as glucose, calcium, and electrolytes, to assess organ function.",
  "comprehensive metabolic panel (CMP)": "A CMP includes the BMP and additional protein and liver enzyme tests.",
  "lipid panel": "A lipid panel measures cholesterol levels, including LDL, HDL, and triglycerides, to assess heart disease risk.",
  "liver function tests": "These tests measure liver enzymes and proteins to assess liver health.",
  "thyroid function tests": "These tests measure thyroid hormones to diagnose thyroid disorders.",
  "hemoglobin A1c": "This test measures average blood glucose levels over the past 2-3 months to monitor diabetes.",
  "vitamin D test": "This test measures vitamin D levels to check for deficiency or toxicity.",
  "iron panel": "An iron panel measures iron levels and related markers to diagnose anemia or iron overload.",
  "kidney function tests": "These tests measure waste products in the blood to assess kidney health.",
  // Blood Pressure
  "high blood pressure": "High blood pressure, or hypertension, increases the risk of heart disease and stroke. Maintain a healthy diet, exercise regularly, and limit salt intake to manage blood pressure.",
  "low blood pressure": "Low blood pressure, or hypotension, can cause dizziness and fainting. Stay hydrated, eat small frequent meals, and avoid standing for long periods.",
  "normal blood pressure": "Normal blood pressure is around 120/80 mmHg. Maintain a healthy lifestyle to keep your blood pressure within this range.",
  // Weight
  "healthy weight": "Maintain a healthy weight by balancing calorie intake with physical activity. Eat a balanced diet and exercise regularly.",
  "weight gain": "To gain weight healthily, increase your calorie intake with nutrient-dense foods and strength training exercises.",
  "weight loss": "For weight loss, reduce calorie intake, increase physical activity, and avoid processed foods. Focus on a balanced diet with plenty of fruits, vegetables, lean proteins, and whole grains.",
  // Height
  "height growth": "Height growth in children and adolescents can be supported by a balanced diet, regular exercise, and adequate sleep. Genetics also play a significant role in determining height.",
  // Cholesterol
  "high cholesterol": "High cholesterol increases the risk of heart disease. Lower cholesterol levels by eating a diet low in saturated fats and trans fats, exercising regularly, and avoiding smoking.",
  "low cholesterol": "Low cholesterol can be achieved through a healthy diet, regular physical activity, and maintaining a healthy weight.",
  "normal cholesterol": "Maintain normal cholesterol levels by eating a balanced diet, exercising regularly, and avoiding smoking and excessive alcohol consumption.",
  // Nutritional Advice
  "fiber-rich foods": "Fiber-rich foods include fruits, vegetables, whole grains, and legumes. Fiber helps with digestion, lowers cholesterol, and controls blood sugar levels.",
  "protein-rich foods": "Protein-rich foods include lean meats, fish, eggs, dairy, beans, and nuts. Protein is essential for muscle repair, immune function, and overall health.",
  "healthy fats": "Healthy fats include avocados, nuts, seeds, and olive oil. These fats support brain health, hormone production, and cell function.",
  "lactose-free foods": "Lactose-free foods include lactose-free dairy products, plant-based milks, and foods naturally low in lactose such as fruits, vegetables, and meats.",
  // Specific Food Advice
  "foods high in vitamin A": "Foods high in vitamin A include carrots, sweet potatoes, spinach, and apricots.",
  "foods high in vitamin B": "Foods high in vitamin B include whole grains, meat, eggs, dairy, legumes, seeds, and leafy greens.",
  "foods high in vitamin C": "Foods high in vitamin C include citrus fruits, strawberries, bell peppers, and broccoli.",
  "foods high in vitamin D": "Foods high in vitamin D include fatty fish, fortified dairy products, and mushrooms.",
  "foods high in vitamin E": "Foods high in vitamin E include nuts, seeds, spinach, and broccoli.",
  "foods high in vitamin K": "Foods high in vitamin K include leafy greens, broccoli, Brussels sprouts, and green beans.",
  // Additional Detailed Information
  "reduce inflammation": "To reduce inflammation, eat anti-inflammatory foods like berries, fatty fish, and green leafy vegetables. Avoid processed foods, sugar, and trans fats.",
  "boost immunity": "Boost your immunity by eating a diet rich in fruits, vegetables, whole grains, and lean proteins. Stay hydrated, get enough sleep, and manage stress.",
  "improve digestion": "Improve digestion by eating high-fiber foods, staying hydrated, and incorporating probiotics like yogurt and fermented foods into your diet.",
  "support mental health": "Support mental health by maintaining a balanced diet, staying physically active, getting enough sleep, and seeking social support.",
  "enhance skin health": "Enhance skin health by staying hydrated, eating a diet rich in antioxidants, and protecting your skin from the sun.",
  "bone health": "For bone health, ensure adequate intake of calcium and vitamin D, engage in weight-bearing exercises, and avoid smoking and excessive alcohol.",
  "reduce stress": "Reduce stress by practicing mindfulness, staying physically active, getting enough sleep, and seeking social support.",
  "improve sleep": "Improve sleep by maintaining a regular sleep schedule, creating a relaxing bedtime routine, and avoiding caffeine and electronics before bed.",
  "heart health": "Maintain heart health by eating a balanced diet low in saturated fats, exercising regularly, avoiding smoking, and managing stress.",
  "eye health": "Support eye health by eating foods rich in vitamin A, such as carrots and leafy greens, and protecting your eyes from UV light.",
  "turmeric": "Turmeric contains curcumin, a powerful anti-inflammatory and antioxidant. It's commonly used in Indian cuisine and can help reduce inflammation.",
  "cumin": "Cumin aids digestion and is rich in iron. It is often used in Indian dishes like curries and dals.",
  "ginger": "Ginger is great for digestion and has anti-inflammatory properties. It is used in teas, curries, and as a spice in various Indian dishes.",
  "garlic": "Garlic boosts the immune system and has antibacterial properties. It is used in a variety of Indian dishes.",
  "fenugreek": "Fenugreek helps in controlling blood sugar levels and improves digestion. It is used in Indian curries and parathas.",
  "cardamom": "Cardamom aids digestion and has detoxifying properties. It is used in Indian sweets and chai.",
  "mustard seeds": "Mustard seeds are rich in selenium and magnesium, which can help reduce inflammation. They are used in tempering dals and curries.",
  "cloves": "Cloves have antibacterial properties and can help with toothaches. They are used in Indian biryanis and garam masala.",
  "coriander": "Coriander aids digestion and is a good source of dietary fiber. It is used as a spice and garnish in many Indian dishes.",
  "curry leaves": "Curry leaves are rich in iron and vitamins. They are used in South Indian dishes and tempering.",
  "mango": "Mangoes are rich in vitamins A and C, and are a good source of fiber. They are enjoyed fresh, in juices, and in dishes like aamras.",
  "banana": "Bananas are a great source of potassium and vitamin B6. They are commonly eaten fresh or used in desserts and snacks.",
  "papaya": "Papayas are rich in vitamin C and aid digestion. They are consumed fresh or in fruit salads.",
  "pomegranate": "Pomegranates are high in antioxidants and vitamin C. They are eaten fresh or used in juices.",
  "coconut": "Coconuts provide healthy fats and are used in various forms, including fresh, dried, and as coconut milk in curries.",
  "almonds": "Almonds are a good source of healthy fats, protein, and vitamin E. They are eaten raw, soaked, or used in sweets like badam halwa.",
  "cashews": "Cashews are rich in healthy fats and minerals. They are used in Indian curries and desserts.",
  "dates": "Dates are high in fiber and natural sugars, making them a great energy booster. They are eaten fresh or used in sweets.",
  "raisin": "Raisins are a good source of iron and energy. They are used in sweets, snacks, and cooking.",
  "lentils": "Lentils are a great source of protein and fiber. They are used in dishes like dal and sambar.",
  "chickpeas": "Chickpeas are rich in protein and fiber. They are used in dishes like chole and hummus.",
  "black beans": "Black beans are high in protein and fiber. They are used in various Indian and fusion dishes.",
  "kidney beans": "Kidney beans are rich in protein and fiber. They are used in dishes like rajma.",
  "toor dal": "Toor dal is a staple in Indian cuisine and is high in protein and fiber.",
  "moong dal": "Moong dal is easily digestible and rich in protein. It is used in soups, khichdi, and dals.",
  "masoor dal": "Masoor dal is a good source of protein and iron. It is used in various dal preparations.",
  "urad dal": "Urad dal is rich in protein and used in dishes like idli, dosa, and dal makhani.",
  "rice": "Rice is a staple food in India and is a good source of energy. Basmati rice is often used in biryanis and pulaos.",
  "whole wheat": "Whole wheat is a good source of fiber and nutrients. It is used in making chapatis, parathas, and bread.",
  "millet": "Millet is rich in fiber and minerals. It is used in dishes like bajra roti and ragi dosa.",
  "oats": "Oats are a good source of soluble fiber and help in lowering cholesterol. They are used in breakfast dishes and snacks.",
  "quinoa": "Quinoa is a high-protein grain that is also rich in fiber. It is used in salads and as a rice substitute.",
  "barley": "Barley is rich in fiber and helps in lowering cholesterol. It is used in soups and as a rice substitute.",
  "amaranth": "Amaranth is a high-protein grain that is also rich in iron. It is used in porridge and snacks.",
  "spinach": "Spinach is rich in iron, vitamins A and C. It is used in dishes like palak paneer and saag.",
  "fenugreek leaves": "Fenugreek leaves are high in iron and fiber. They are used in dishes like methi paratha and methi malai matar.",
  "mustard greens": "Mustard greens are rich in vitamins A and C. They are used in dishes like sarson ka saag.",
  "cabbage": "Cabbage is low in calories and high in vitamins C and K. It is used in salads, stir-fries, and curries.",
  "cauliflower": "Cauliflower is rich in vitamins C and K. It is used in dishes like aloo gobi and gobi paratha.",
  "broccoli": "Broccoli is high in vitamins C and K, and fiber. It is used in salads, stir-fries, and as a side dish.",
  "okra": "Okra is rich in fiber and vitamins C and K. It is used in dishes like bhindi masala and sambar.",
  "eggplant": "Eggplant is high in fiber and antioxidants. It is used in dishes like baingan bharta and vangi bath.",
  "tomato": "Tomatoes are rich in vitamins C and K. They are used in salads, curries, and as a base for sauces.",
  "onion": "Onions are rich in antioxidants and add flavor to many Indian dishes.",
  "garlic": "Garlic has antibacterial properties and boosts the immune system. It is used in a variety of Indian dishes.",
  "carrot": "Carrots are rich in beta-carotene and fiber. They are used in salads, curries, and desserts like gajar ka halwa.",
  "beetroot": "Beetroot is high in iron and folate. It is used in salads, juices, and curries.",
  "radish": "Radishes are low in calories and high in fiber. They are used in salads and parathas.",
  "potato": "Potatoes are a good source of energy and potassium. They are used in a variety of dishes like aloo paratha and dum aloo.",
  "sweet potato": "Sweet potatoes are rich in beta-carotene and fiber. They are used in snacks, curries, and desserts.",
  "pumpkin": "Pumpkins are high in vitamins A and C. They are used in soups, curries, and desserts like pumpkin halwa.",
  "bottle gourd": "Bottle gourd is low in calories and helps in digestion. It is used in curries and soups.",
  "bitter gourd": "Bitter gourd helps in controlling blood sugar levels. It is used in curries and as a stir-fry.",
  "ridge gourd": "Ridge gourd is low in calories and high in fiber. It is used in curries and stir-fries.",
  "snake gourd": "Snake gourd is low in calories and helps in digestion. It is used in curries and stir-fries.",
  "drumstick": "Drumsticks are rich in vitamins and minerals. They are used in sambar and curries.",
  "green peas": "Green peas are rich in protein and fiber. They are used in curries, pulaos, and snacks like matar kachori.",
  "coriander leaves": "Coriander leaves are rich in vitamins A and C. They are used as a garnish in many Indian dishes.",
  "mint leaves": "Mint leaves aid digestion and are used in chutneys and raitas.",
  "curry leaves": "Curry leaves are rich in iron and vitamins. They are used in South Indian dishes and tempering.",
  "coconut": "Coconut provides healthy fats and is used in various forms, including fresh, dried, and as coconut milk in curries.",
  "peanuts": "Peanuts are a good source of protein and healthy fats. They are used in snacks, chutneys, and curries.",
  "sesame seeds": "Sesame seeds are rich in calcium and iron. They are used in sweets, snacks, and as a garnish.",
  "flaxseeds": "Flaxseeds are high in omega-3 fatty acids and fiber. They are used in snacks, smoothies, and as a garnish.",
  "sunflower seeds": "Sunflower seeds are rich in healthy fats and vitamins. They are used in snacks and salads.",
  "pumpkin seeds": "Pumpkin seeds are high in magnesium and zinc. They are used in snacks and salads.",
  "chia seeds": "Chia seeds are rich in omega-3 fatty acids and fiber. They are used in smoothies, puddings, and snacks.",
  "jaggery": "Jaggery is a traditional Indian sweetener that is rich in iron. It is used in sweets and snacks.",
  "honey": "Honey is a natural sweetener with antibacterial properties. It is used in sweets, snacks, and drinks.",
  "ghee": "Ghee is a traditional Indian clarified butter that is rich in healthy fats. It is used in cooking and as a topping for foods.",
  "yogurt": "Yogurt is rich in probiotics and helps in digestion. It is used in curries, raitas, and as a side dish.",
  "paneer": "Paneer is a good source of protein and calcium. It is used in curries, snacks, and desserts.",
  "milk": "Milk is a good source of calcium and vitamin D. It is used in drinks, desserts, and cooking.",
  "buttermilk": "Buttermilk aids digestion and is consumed as a drink or used in cooking.",
  "lassi": "Lassi is a traditional Indian yogurt drink that aids digestion. It is consumed plain or flavored with fruits.",
  "almond milk": "Almond milk is a dairy-free alternative that is rich in vitamin E. It is used in drinks and cooking.",
  "soy milk": "Soy milk is a dairy-free alternative that is rich in protein. It is used in drinks and cooking.",
  "coconut milk": "Coconut milk is rich in healthy fats and is used in curries and desserts.",
  "tea": "Tea is a popular Indian beverage that is rich in antioxidants. It is consumed plain or with spices like cardamom and ginger.",
  "coffee": "Coffee is a popular beverage that boosts energy. It is consumed plain or with milk and sugar.",
  "green tea": "Green tea is rich in antioxidants and aids in weight loss. It is consumed plain or flavored.",


  "high protein foods": "High protein foods include lean meats, fish, eggs, dairy, beans, and nuts.",
  "low protein foods": "Low protein foods include fruits, vegetables, and foods high in carbohydrates like bread and pasta.",
  "high fiber foods": "High fiber foods include fruits, vegetables, whole grains, and legumes.",
  "low fiber foods": "Low fiber foods include white bread, white rice, and other refined grains.",
  "high fat foods": "High fat foods include avocados, nuts, seeds, and oils such as olive oil.",
  "low fat foods": "Low fat foods include fruits, vegetables, and lean proteins like chicken and fish.",
  "high carb foods": "High carb foods include bread, rice, pasta, and starchy vegetables like potatoes.",
  "low carb foods": "Low carb foods include leafy greens, non-starchy vegetables, and lean meats.",
  "high sugar foods": "High sugar foods include candies, pastries, sodas, and other sweetened beverages.",
  "low sugar foods": "Low sugar foods include unsweetened dairy products, vegetables, and whole grains.",
  "high vitamin C foods": "Foods high in vitamin C include citrus fruits, strawberries, bell peppers, and broccoli.",
  "low vitamin C foods": "Low vitamin C foods include grains, meats, and dairy products.",
  "recipes for diabetes": "For diabetes, try recipes like baked salmon with steamed vegetables, quinoa salad with vegetables, and Greek yogurt with berries.",
  "recipes for high blood pressure": "For high blood pressure, try recipes like grilled chicken with roasted vegetables, oatmeal with fruits, and spinach salad with nuts and seeds.",
  "recipes for cholesterol management": "For cholesterol management, try recipes like avocado toast, lentil soup, and mixed bean salad.",
  "recipes for weight loss": "For weight loss, try recipes like vegetable stir-fry with tofu, grilled chicken with a side salad, and smoothies with spinach, berries, and protein powder.",
  "recipes for weight gain": "For weight gain, try recipes like peanut butter and banana smoothie, whole grain pasta with meat sauce, and avocado and egg toast.",
  "foods to avoid for diabetes": "Avoid sugary foods, refined carbs, and trans fats. Focus on whole grains, vegetables, lean proteins, and healthy fats.",
  "foods to avoid for high blood pressure": "Avoid high-sodium foods, processed foods, and excessive alcohol. Focus on fruits, vegetables, whole grains, and lean proteins.",
  "foods to avoid for high cholesterol": "Avoid trans fats, saturated fats, and excessive sugar. Focus on fiber-rich foods, healthy fats, and lean proteins.",
  "foods to eat for healthy skin": "For healthy skin, eat foods rich in vitamins A, C, and E such as carrots, citrus fruits, nuts, and seeds.",
  "foods to eat for healthy hair": "For healthy hair, consume foods rich in biotin, protein, and omega-3 fatty acids such as eggs, fish, and walnuts.",
  "foods to eat for strong bones": "For strong bones, eat foods high in calcium and vitamin D such as dairy products, leafy greens, and fortified cereals.",
  "foods to eat for energy": "For sustained energy, eat complex carbs, lean proteins, and healthy fats such as whole grains, chicken, and avocados.",
  "foods to avoid for better sleep": "Avoid caffeine, heavy meals, and alcohol before bedtime. Focus on foods that promote sleep such as bananas, almonds, and chamomile tea.",
  "high protein vegetarian foods": "Include paneer, tofu, lentils, chickpeas, quinoa, and almonds.",
  "high omega-3 foods": "Include flaxseeds, chia seeds, walnuts, and fatty fish like salmon and mackerel.",
  "high antioxidant foods": "Include berries, dark chocolate, pecans, and kidney beans.",
  "high folate foods": "Include spinach, lentils, chickpeas, and asparagus.",
  "high selenium foods": "Include Brazil nuts, sunflower seeds, and fish like tuna and halibut.",
  "high iodine foods": "Include seaweed, fish, dairy, and iodized salt.",
  "high manganese foods": "Include pineapple, whole grains, nuts, and spinach.",
  "high copper foods": "Include shellfish, seeds, nuts, and organ meats.",
  "high phosphorus foods": "Include meat, fish, dairy, and whole grains.",
  "high riboflavin foods": "Include eggs, organ meats, and green vegetables.",
  "high pantothenic acid foods": "Include chicken, beef, potatoes, and oats.",
  "high thiamine foods": "Include whole grains, pork, and legumes.",
  "high niacin foods": "Include meat, fish, and peanuts.",
  "high biotin foods": "Include eggs, almonds, and sweet potatoes.",
  "high choline foods": "Include eggs, beef, and cruciferous vegetables.",
  "high lycopene foods": "Include tomatoes, watermelon, and pink grapefruit.",
  "high lutein foods": "Include kale, spinach, and corn.",
  "high zeaxanthin foods": "Include eggs, oranges, and leafy greens.",
  
  // Low nutrient foods
  "low oxalate foods": "Include white rice, bananas, and certain meats.",
  "low purine foods": "Include low-fat dairy, most fruits, and vegetables.",
  "low glycemic index foods": "Include lentils, chickpeas, and whole grains.",
  "low calorie foods": "Include leafy greens, cucumbers, and mushrooms.",
  "low carbohydrate vegetables": "Include bell peppers, broccoli, and zucchini.",
  "low phosphorus foods": "Include fruits like apples, grapes, and strawberries.",
  "low histamine foods": "Include fresh meat, poultry, and fish.",
  "low tyramine foods": "Include fresh vegetables, certain grains, and eggs.",
  "low goitrogen foods": "Include citrus fruits, bell peppers, and lean meats.",
  "low FODMAP foods": "Include carrots, cucumbers, and green beans.",
  
  // Disease-specific food advice
  "foods for liver health": "Include garlic, beets, carrots, and green tea.",
  "foods for gallbladder health": "Include pears, brown rice, and beets.",
  "foods for lung health": "Include apples, turmeric, and ginger.",
  "foods for gut health": "Include yogurt, kimchi, and whole grains.",
  "foods for arthritis": "Include fatty fish, garlic, and broccoli.",
  "foods for gout": "Include cherries, coffee, and water.",
  "foods for high uric acid": "Include cherries, strawberries, and high-fiber vegetables.",
  "foods for inflammation": "Include turmeric, berries, and olive oil.",
  "foods for skin health": "Include avocados, walnuts, and sunflower seeds.",
  "foods for hair health": "Include eggs, berries, and nuts.",
  "foods for nail health": "Include leafy greens, eggs, and salmon.",
  "foods for dental health": "Include cheese, yogurt, and leafy greens.",
  "foods for eye health": "Include fish, nuts, and seeds.",
  "foods for bone health": "Include dairy, leafy greens, and fish.",
  "foods for brain health": "Include fatty fish, blueberries, and turmeric.",
  "foods for immune health": "Include citrus fruits, red bell peppers, and almonds.",
  "foods for digestive health": "Include ginger, bananas, and oats.",
  "foods for energy": "Include bananas, fatty fish, and brown rice.",
  "foods for mental health": "Include fatty fish, dark chocolate, and whole grains.",
  "foods for stress relief": "Include green tea, dark chocolate, and avocados.",
  "foods for sleep": "Include almonds, turkey, and chamomile tea.",
  "foods for concentration": "Include blueberries, pumpkin seeds, and oranges.",
  "foods for heartburn": "Include oatmeal, ginger, and non-citrus fruits.",
  "foods for ulcers": "Include cabbage, licorice, and honey.",
  "foods for acid reflux": "Include bananas, melons, and ginger.",
  "foods for IBS": "Include lean meats, eggs, and low-FODMAP vegetables.",
  "foods for constipation": "Include prunes, apples, and whole grains.",
  "foods for diarrhea": "Include bananas, rice, and toast.",
  "foods for nausea": "Include ginger, crackers, and peppermint.",
  "foods for high blood pressure": "Include leafy greens, berries, and oatmeal.",
  "foods for low blood pressure": "Include salty foods, coffee, and fluids.",
  "foods for cholesterol": "Include oats, barley, and beans.",
  "foods for blood sugar control": "Include cinnamon, green leafy vegetables, and chia seeds.",
  "foods for diabetes management": "Include bitter gourd, fenugreek, and amla.",
  "foods for thyroid health": "Include seaweed, fish, and eggs.",
  "foods for menopause": "Include soybeans, flaxseeds, and legumes.",
  "foods for pregnancy": "Include folate-rich foods, iron-rich foods, and protein-rich foods.",
  "foods for lactation": "Include oats, fenugreek, and garlic.",
  "foods for PCOS": "Include cinnamon, flaxseed, and whole grains.",
  "foods for endometriosis": "Include leafy greens, berries, and fatty fish.",
  "foods for PMS relief": "Include leafy greens, nuts, and seeds.",
  "foods for hormone balance": "Include healthy fats, protein, and fiber.",
  "foods for boosting testosterone": "Include tuna, egg yolks, and oysters.",
  "foods for boosting estrogen": "Include flaxseeds, soy products, and dried fruits.",
  "foods for adrenal fatigue": "Include sea salt, lean meats, and high-vitamin C foods.",
  "foods for detoxification": "Include lemon water, beetroot, and green tea.",
  "foods for anti-aging": "Include avocados, blueberries, and dark chocolate.",
  "foods for longevity": "Include nuts, leafy greens, and whole grains.",
  "foods for reducing cellulite": "Include green tea, apple cider vinegar, and omega-3 fatty acids.",
  "foods for dry skin": "Include avocado, salmon, and olive oil.",
  "foods for oily skin": "Include cucumbers, whole grains, and green tea.",
  "foods for acne-prone skin": "Include fatty fish, nuts, and dark chocolate.",
  "foods for glowing skin": "Include papaya, oranges, and carrots.",
  "foods for strong nails": "Include biotin-rich foods like eggs, almonds, and sweet potatoes.",
  "foods for healthy gums": "Include cheese, apples, and leafy greens.",
  "foods for fresh breath": "Include yogurt, parsley, and apples.",
  "foods for cold sores": "Include lysine-rich foods like fish, chicken, and beans.",
  "foods for wound healing": "Include protein-rich foods, vitamin C-rich foods, and zinc-rich foods.",
  "foods for boosting metabolism": "Include green tea, chili peppers, and coffee.",
  "foods for reducing wrinkles": "Include avocado, salmon, and nuts.",
  "foods for hydration": "Include cucumbers, watermelon, and strawberries.",
  "foods for weight management": "Include lean proteins, whole grains, and plenty of vegetables.",
  "foods for reducing belly fat": "Include green tea, avocados, and fiber-rich foods.",
  "foods for muscle building": "Include chicken breast, eggs, and sweet potatoes.",
  "foods for joint health": "Include turmeric, ginger, and omega-3 fatty acids.",
  "foods for reducing stress": "Include dark chocolate, chamomile tea, and oatmeal.",
  "foods for cognitive function": "Include fatty fish, blueberries, and turmeric.",
  "foods for mental clarity": "Include walnuts, pumpkin seeds, and oranges.",
  "foods for preventing anemia": "Include spinach, lentils, and fortified cereals.",
  "foods for boosting immunity": "Include citrus fruits, ginger, and garlic.",
  "foods for managing allergies": "Include local honey, pineapple, and apples.",
  "foods for managing asthma": "Include carrots, coffee, and avocados.",
  "foods for healthy hair": "Include eggs, spinach, and sweet potatoes.",
  "foods for preventing dandruff": "Include fish, nuts, and leafy greens.",
  "foods for healthy scalp": "Include aloe vera juice, green tea, and coconut oil.",
  "foods for managing eczema": "Include fatty fish, probiotics, and anti-inflammatory foods.",
  "foods for managing psoriasis": "Include fatty fish, omega-3 supplements, and plant-based oils.",
  "foods for managing rosacea": "Include anti-inflammatory foods like leafy greens, fatty fish, and berries.",
  "foods for managing gout": "Include cherries, coffee, and vitamin C-rich foods.",
  "foods for managing hypertension": "Include bananas, beets, and leafy greens.",
  "foods for managing cholesterol": "Include oats, barley, and lentils.",
  "foods for managing blood sugar": "Include bitter melon, fenugreek seeds, and cinnamon.",
  "foods for managing thyroid issues": "Include seaweed, dairy, and eggs.",
  "foods for managing menopause symptoms": "Include soy products, flaxseeds, and whole grains.",
  "foods for managing PMS symptoms": "Include magnesium-rich foods, leafy greens, and whole grains.",
  "foods for managing adrenal fatigue": "Include high-vitamin C foods, sea salt, and lean proteins.",
  "foods for detoxifying the body": "Include lemon water, beetroot, and green tea.",
  "foods for anti-aging benefits": "Include blueberries, avocados, and dark chocolate.",
  "foods for longevity and vitality": "Include nuts, leafy greens, and whole grains.",
  "foods for reducing cellulite": "Include apple cider vinegar, green tea, and omega-3 fatty acids.",
  "foods for dry skin": "Include salmon, avocado, and olive oil.",
  "foods for oily skin": "Include whole grains, cucumbers, and green tea.",
  "foods for acne-prone skin": "Include nuts, fatty fish, and dark chocolate.",
  "foods for a glowing complexion": "Include papaya, carrots, and oranges.",
  "foods for strong and healthy nails": "Include eggs, biotin-rich foods, and almonds.",
  "foods for healthy gums and teeth": "Include apples, cheese, and leafy greens.",
  "foods for fresh breath": "Include parsley, yogurt, and apples.",
  "foods for cold sore prevention": "Include lysine-rich foods like chicken, fish, and beans.",
  "foods for wound healing": "Include protein-rich foods, vitamin C-rich foods, and zinc-rich foods.",
  "foods for boosting metabolism": "Include green tea, chili peppers, and coffee.",
  "foods for reducing wrinkles": "Include avocado, salmon, and nuts.",
  "foods for maintaining hydration": "Include cucumbers, watermelon, and strawberries.",
  "foods for weight management": "Include lean proteins, whole grains, and plenty of vegetables.",
  "foods for reducing belly fat": "Include green tea, avocados, and fiber-rich foods.",
  "foods for building muscle": "Include chicken breast, eggs, and sweet potatoes.",
  "foods for joint health": "Include turmeric, ginger, and omega-3 fatty acids.",
  "foods for reducing stress": "Include dark chocolate, chamomile tea, and oatmeal.",
  "foods for cognitive function": "Include fatty fish, blueberries, and turmeric.",
  "foods for mental clarity": "Include walnuts, pumpkin seeds, and oranges.",
  "foods for preventing anemia": "Include spinach, lentils, and fortified cereals.",
  "foods for boosting immunity": "Include citrus fruits, ginger, and garlic.",
  "foods for managing allergies": "Include local honey, pineapple, and apples.",
  "foods for managing asthma": "Include carrots, coffee, and avocados.",
  "foods for healthy hair": "Include eggs, spinach, and sweet potatoes.",
  "foods for preventing dandruff": "Include fish, nuts, and leafy greens.",
  "foods for a healthy scalp": "Include aloe vera juice, green tea, and coconut oil.",
  "foods for managing eczema": "Include fatty fish, probiotics, and anti-inflammatory foods.",
  "foods for managing psoriasis": "Include fatty fish, omega-3 supplements, and plant-based oils.",
  "foods for managing rosacea": "Include anti-inflammatory foods like leafy greens, fatty fish, and berries.",
  "foods for managing gout": "Include cherries, coffee, and vitamin C-rich foods.",
  "foods for managing hypertension": "Include bananas, beets, and leafy greens.",
  "foods for managing cholesterol": "Include oats, barley, and lentils.",
  "foods for managing blood sugar": "Include bitter melon, fenugreek seeds, and cinnamon.",
  "foods for managing thyroid issues": "Include seaweed, dairy, and eggs.",
  "foods for managing menopause symptoms": "Include soy products, flaxseeds, and whole grains.",
  "foods for managing PMS symptoms": "Include magnesium-rich foods, leafy greens, and whole grains.",
  "foods for managing adrenal fatigue": "Include high-vitamin C foods, sea salt, and lean proteins.",
  "foods for detoxifying the body": "Include lemon water, beetroot, and green tea.",
  "foods for anti-aging benefits": "Include blueberries, avocados, and dark chocolate.",
  "foods for longevity and vitality": "Include nuts, leafy greens, and whole grains.",
  "foods for reducing cellulite": "Include apple cider vinegar, green tea, and omega-3 fatty acids.",
  "foods for dry skin": "Include salmon, avocado, and olive oil.",
  "foods for oily skin": "Include whole grains, cucumbers, and green tea.",
  "foods for acne-prone skin": "Include nuts, fatty fish, and dark chocolate.",
};

function refineQuestion(question) {
  return question.toLowerCase().replace(/[^a-z0-9\s]/gi, '').trim();
}

exports.getHealthAdvice = async (req, res) => {
  const { question } = req.body;

  try {
    const refinedQuestion = refineQuestion(question);
    const words = refinedQuestion.split(' ');

    let foundAdvice = null;

    // Check for exact matches first
    for (const key of Object.keys(healthAdvices)) {
      if (refinedQuestion.includes(key)) {
        foundAdvice = healthAdvices[key];
        console.log(`Exact match found for key: ${key}`);
        break;
      }
    }

    // If no exact matches, check for partial matches
    if (!foundAdvice) {
      for (const word of words) {
        for (const key of Object.keys(healthAdvices)) {
          if (key.includes(word) || word.includes(key)) {
            foundAdvice = healthAdvices[key];
            console.log(`Partial match found for word: ${word} in key: ${key}`);
            break;
          }
        }
        if (foundAdvice) break;
      }
    }

    if (foundAdvice) {
      res.status(200).json({ advice: foundAdvice });
    } else {
      res.status(404).json({ error: 'No advice found for your query.' });
    }
  } catch (error) {
    console.error('Error fetching health advice:', error);
    res.status(500).json({ error: 'An error occurred while fetching health advice.' });
  }
};